[
  {
    "fullName": "Aisha Khan",
    "email": "aisha.khan@example.com",
    "passwordHash": "hashed_password_1",
    "profilePhoto": "https://example.com/photos/aisha.jpg",
    "age": 24,
    "gender": "Female",
    "country": "Pakistan",
    "jobRole": "Software Engineering Student",
    "industry": "IT",
    "experienceYears": 0,
    "mentorshipTopics": ["Web Development", "Interview Prep"],
    "bio": "Final-year CS student passionate about front-end development and building scalable applications.",
    "availability": ["Weekdays", "Evenings"],
    "languages": ["English", "Urdu"],
    "linkedIn": "https://linkedin.com/in/aishakhan",
    "website": ""
  },
  {
    "fullName": "David Lee",
    "email": "david.lee@example.com",
    "passwordHash": "hashed_password_2",
    "profilePhoto": "https://example.com/photos/david.jpg",
    "age": 30,
    "gender": "Male",
    "country": "USA",
    "jobRole": "Junior Developer",
    "industry": "IT",
    "experienceYears": 2,
    "mentorshipTopics": ["Machine Learning", "Portfolio Building"],
    "bio": "Self-taught developer aiming to transition into data science and AI-focused solutions.",
    "availability": ["Weekends"],
    "languages": ["English", "Spanish"],
    "linkedIn": "https://linkedin.com/in/davidlee",
    "website": "https://davidlee.dev"
  },
  {
    "fullName": "Maria Gonzalez",
    "email": "maria.g@example.com",
    "passwordHash": "hashed_password_3",
    "profilePhoto": "https://example.com/photos/maria.jpg",
    "age": 27,
    "gender": "Female",
    "country": "Mexico",
    "jobRole": "UX Designer",
    "industry": "Design",
    "experienceYears": 3,
    "mentorshipTopics": ["Career Growth", "Portfolio Review"],
    "bio": "Creative designer focused on crafting user-friendly and visually appealing interfaces.",
    "availability": ["Weekdays", "Weekends"],
    "languages": ["Spanish", "English"],
    "linkedIn": "",
    "website": "https://mariaux.com"
  },
  {
    "fullName": "Ahmed Raza",
    "email": "ahmed.raza@example.com",
    "passwordHash": "hashed_password_4",
    "profilePhoto": "https://example.com/photos/ahmed.jpg",
    "age": 22,
    "gender": "Male",
    "country": "Pakistan",
    "jobRole": "Student",
    "industry": "Cybersecurity",
    "experienceYears": 0,
    "mentorshipTopics": ["Ethical Hacking", "Certification Guidance"],
    "bio": "Tech enthusiast with a growing interest in network and application security.",
    "availability": ["Evenings"],
    "languages": ["English", "Urdu"],
    "linkedIn": "https://linkedin.com/in/ahmedraza",
    "website": ""
  },
  {
    "fullName": "Emily Carter",
    "email": "emily.carter@example.com",
    "passwordHash": "hashed_password_5",
    "profilePhoto": "https://example.com/photos/emily.jpg",
    "age": 35,
    "gender": "Female",
    "country": "Canada",
    "jobRole": "Senior Data Analyst",
    "industry": "Data Science",
    "experienceYears": 8,
    "mentorshipTopics": ["Leadership Skills", "Data Visualization"],
    "bio": "Experienced data analyst with a passion for mentoring and storytelling with data.",
    "availability": ["Weekdays"],
    "languages": ["English", "French"],
    "linkedIn": "https://linkedin.com/in/emilycarter",
    "website": ""
  },
  {
    "fullName": "Hiroshi Tanaka",
    "email": "hiroshi.t@example.com",
    "passwordHash": "hashed_password_6",
    "profilePhoto": "https://example.com/photos/hiroshi.jpg",
    "age": 28,
    "gender": "Male",
    "country": "Japan",
    "jobRole": "Software Engineer",
    "industry": "Robotics",
    "experienceYears": 5,
    "mentorshipTopics": ["AI Projects", "Technical Interviews"],
    "bio": "Engineer specializing in robotics and automation solutions for industrial use.",
    "availability": ["Weekends", "Evenings"],
    "languages": ["Japanese", "English"],
    "linkedIn": "",
    "website": "https://hiroshitech.com"
  },
  {
    "fullName": "Sarah Johnson",
    "email": "sarah.j@example.com",
    "passwordHash": "hashed_password_7",
    "profilePhoto": "https://example.com/photos/sarah.jpg",
    "age": 26,
    "gender": "Female",
    "country": "UK",
    "jobRole": "Graduate",
    "industry": "Product Management",
    "experienceYears": 1,
    "mentorshipTopics": ["Career Switching", "Interview Prep"],
    "bio": "Aspiring product manager with a marketing background and user-centric mindset.",
    "availability": ["Weekdays", "Weekends"],
    "languages": ["English"],
    "linkedIn": "https://linkedin.com/in/sarahjohnson",
    "website": ""
  },
  {
    "fullName": "Mohammed Al-Sayed",
    "email": "mohammed.s@example.com",
    "passwordHash": "hashed_password_8",
    "profilePhoto": "https://example.com/photos/mohammed.jpg",
    "age": 32,
    "gender": "Male",
    "country": "UAE",
    "jobRole": "Project Manager",
    "industry": "IT",
    "experienceYears": 7,
    "mentorshipTopics": ["Leadership", "Agile Practices"],
    "bio": "Project manager with a focus on delivering quality tech solutions on time.",
    "availability": ["Weekdays"],
    "languages": ["Arabic", "English"],
    "linkedIn": "https://linkedin.com/in/mohammedalsayed",
    "website": ""
  },
  {
    "fullName": "Olivia Brown",
    "email": "olivia.b@example.com",
    "passwordHash": "hashed_password_9",
    "profilePhoto": "https://example.com/photos/olivia.jpg",
    "age": 21,
    "gender": "Female",
    "country": "Australia",
    "jobRole": "Student",
    "industry": "Game Development",
    "experienceYears": 0,
    "mentorshipTopics": ["Unity", "C# Programming"],
    "bio": "Game design student eager to learn from industry professionals.",
    "availability": ["Weekends"],
    "languages": ["English"],
    "linkedIn": "",
    "website": ""
  },
  {
    "fullName": "Carlos Mendes",
    "email": "carlos.m@example.com",
    "passwordHash": "hashed_password_10",
    "profilePhoto": "https://example.com/photos/carlos.jpg",
    "age": 29,
    "gender": "Male",
    "country": "Brazil",
    "jobRole": "Frontend Developer",
    "industry": "Web Development",
    "experienceYears": 4,
    "mentorshipTopics": ["React", "Career Growth"],
    "bio": "Frontend developer building scalable, user-focused web applications.",
    "availability": ["Evenings"],
    "languages": ["Portuguese", "English"],
    "linkedIn": "https://linkedin.com/in/carlosmendes",
    "website": ""
  }
]


[
  {
    "fullName": "Priya Sharma",
    "email": "priya.sharma@example.com",
    "passwordHash": "hashed_password_11",
    "profilePhoto": "https://example.com/photos/priya.jpg",
    "age": 25,
    "gender": "Female",
    "country": "India",
    "jobRole": "Data Scientist",
    "industry": "AI & Analytics",
    "experienceYears": 2,
    "mentorshipTopics": ["Machine Learning", "Python"],
    "bio": "Data scientist focused on predictive analytics and natural language processing.",
    "availability": ["Weekdays", "Evenings"],
    "languages": ["Hindi", "English"],
    "linkedIn": "https://linkedin.com/in/priyasharma",
    "website": ""
  },
  {
    "fullName": "John Smith",
    "email": "john.smith@example.com",
    "passwordHash": "hashed_password_12",
    "profilePhoto": "https://example.com/photos/john.jpg",
    "age": 40,
    "gender": "Male",
    "country": "USA",
    "jobRole": "CTO",
    "industry": "FinTech",
    "experienceYears": 15,
    "mentorshipTopics": ["Startup Growth", "Tech Leadership"],
    "bio": "CTO with over 15 years of experience in scaling financial technology products.",
    "availability": ["Weekdays"],
    "languages": ["English"],
    "linkedIn": "https://linkedin.com/in/johnsmith",
    "website": "https://johnsmith.io"
  },
  {
    "fullName": "Fatima Noor",
    "email": "fatima.noor@example.com",
    "passwordHash": "hashed_password_13",
    "profilePhoto": "https://example.com/photos/fatima.jpg",
    "age": 23,
    "gender": "Female",
    "country": "Pakistan",
    "jobRole": "Content Writer",
    "industry": "Marketing",
    "experienceYears": 1,
    "mentorshipTopics": ["SEO", "Content Strategy"],
    "bio": "Creative writer passionate about digital storytelling and brand building.",
    "availability": ["Weekends"],
    "languages": ["Urdu", "English"],
    "linkedIn": "",
    "website": ""
  },
  {
    "fullName": "Liam O'Connor",
    "email": "liam.oconnor@example.com",
    "passwordHash": "hashed_password_14",
    "profilePhoto": "https://example.com/photos/liam.jpg",
    "age": 34,
    "gender": "Male",
    "country": "Ireland",
    "jobRole": "Cloud Architect",
    "industry": "IT Infrastructure",
    "experienceYears": 10,
    "mentorshipTopics": ["AWS", "DevOps"],
    "bio": "Helping businesses migrate and scale in the cloud with security in mind.",
    "availability": ["Weekdays", "Evenings"],
    "languages": ["English"],
    "linkedIn": "https://linkedin.com/in/liamoconnor",
    "website": ""
  },
  {
    "fullName": "Sophia Martinez",
    "email": "sophia.martinez@example.com",
    "passwordHash": "hashed_password_15",
    "profilePhoto": "https://example.com/photos/sophia.jpg",
    "age": 31,
    "gender": "Female",
    "country": "Spain",
    "jobRole": "Business Analyst",
    "industry": "Finance",
    "experienceYears": 6,
    "mentorshipTopics": ["Business Strategy", "Stakeholder Management"],
    "bio": "Experienced analyst bridging the gap between tech teams and business leaders.",
    "availability": ["Weekdays", "Weekends"],
    "languages": ["Spanish", "English"],
    "linkedIn": "https://linkedin.com/in/sophiamartinez",
    "website": ""
  },
  {
    "fullName": "Omar Farouk",
    "email": "omar.farouk@example.com",
    "passwordHash": "hashed_password_16",
    "profilePhoto": "https://example.com/photos/omar.jpg",
    "age": 29,
    "gender": "Male",
    "country": "Egypt",
    "jobRole": "Backend Developer",
    "industry": "Web Development",
    "experienceYears": 5,
    "mentorshipTopics": ["API Design", "Microservices"],
    "bio": "Backend engineer creating robust APIs and optimizing server-side performance.",
    "availability": ["Evenings"],
    "languages": ["Arabic", "English"],
    "linkedIn": "",
    "website": ""
  },
  {
    "fullName": "Hannah Kim",
    "email": "hannah.kim@example.com",
    "passwordHash": "hashed_password_17",
    "profilePhoto": "https://example.com/photos/hannah.jpg",
    "age": 22,
    "gender": "Female",
    "country": "South Korea",
    "jobRole": "Graphic Designer",
    "industry": "Creative Arts",
    "experienceYears": 1,
    "mentorshipTopics": ["Brand Identity", "Adobe Creative Suite"],
    "bio": "Graphic designer passionate about branding and impactful visuals.",
    "availability": ["Weekends"],
    "languages": ["Korean", "English"],
    "linkedIn": "https://linkedin.com/in/hannahkim",
    "website": ""
  },
  {
    "fullName": "Alexander Ivanov",
    "email": "alex.ivanov@example.com",
    "passwordHash": "hashed_password_18",
    "profilePhoto": "https://example.com/photos/alex.jpg",
    "age": 37,
    "gender": "Male",
    "country": "Russia",
    "jobRole": "AI Researcher",
    "industry": "Artificial Intelligence",
    "experienceYears": 12,
    "mentorshipTopics": ["Deep Learning", "AI Ethics"],
    "bio": "Researcher exploring the ethical and technical challenges of AI adoption.",
    "availability": ["Weekdays"],
    "languages": ["Russian", "English"],
    "linkedIn": "",
    "website": "https://alexivanov.ai"
  },
  {
    "fullName": "Julia Roberts",
    "email": "julia.roberts@example.com",
    "passwordHash": "hashed_password_19",
    "profilePhoto": "https://example.com/photos/julia.jpg",
    "age": 28,
    "gender": "Female",
    "country": "USA",
    "jobRole": "Full Stack Developer",
    "industry": "IT",
    "experienceYears": 4,
    "mentorshipTopics": ["React", "Node.js"],
    "bio": "Developer working across the stack with a passion for clean, maintainable code.",
    "availability": ["Weekdays", "Weekends"],
    "languages": ["English"],
    "linkedIn": "https://linkedin.com/in/juliarobertsdev",
    "website": ""
  },
  {
    "fullName": "Mateo Silva",
    "email": "mateo.silva@example.com",
    "passwordHash": "hashed_password_20",
    "profilePhoto": "https://example.com/photos/mateo.jpg",
    "age": 33,
    "gender": "Male",
    "country": "Argentina",
    "jobRole": "Mobile App Developer",
    "industry": "Software Development",
    "experienceYears": 6,
    "mentorshipTopics": ["Flutter", "App Monetization"],
    "bio": "Building high-quality cross-platform apps with a focus on user experience.",
    "availability": ["Evenings", "Weekends"],
    "languages": ["Spanish", "English"],
    "linkedIn": "https://linkedin.com/in/mateosilva",
    "website": ""
  }
]
