[
  {
    "fullName": "Aisha Khan",
    "email": "aisha.khan@example.com",
    "password": "hashed_password_1",
    "profilePhoto": "https://example.com/photos/aisha.jpg",
    "age": 24,
    "gender": "Female",
    "country": "Pakistan",
    "currentRole": "Student",
    "industryInterest": "Software Development",
    "experienceYears": 0,
    "mentorshipGoals": ["Web Development", "Interview Prep"],
    "bio": "Final-year CS student passionate about front-end development.",
    "availability": ["Weekdays", "Evenings"],
    "languages": ["English", "Urdu"],
    "linkedIn": "https://linkedin.com/in/aishakhan",
    "website": ""
  },
  {
    "fullName": "David Lee",
    "email": "david.lee@example.com",
    "password": "hashed_password_2",
    "profilePhoto": "https://example.com/photos/david.jpg",
    "age": 30,
    "gender": "Male",
    "country": "USA",
    "currentRole": "Junior Developer",
    "industryInterest": "Data Science",
    "experienceYears": 2,
    "mentorshipGoals": ["Machine Learning", "Portfolio Building"],
    "bio": "Self-taught developer aiming to transition into data science.",
    "availability": ["Weekends"],
    "languages": ["English", "Spanish"],
    "linkedIn": "https://linkedin.com/in/davidlee",
    "website": "https://davidlee.dev"
  },
  {
    "fullName": "Maria Gonzalez",
    "email": "maria.g@example.com",
    "password": "hashed_password_3",
    "profilePhoto": "https://example.com/photos/maria.jpg",
    "age": 27,
    "gender": "Female",
    "country": "Mexico",
    "currentRole": "UX Designer",
    "industryInterest": "UI/UX",
    "experienceYears": 3,
    "mentorshipGoals": ["Career Growth", "Portfolio Review"],
    "bio": "Creative designer focused on user-centric solutions.",
    "availability": ["Weekdays", "Weekends"],
    "languages": ["Spanish", "English"],
    "linkedIn": "",
    "website": "https://mariaux.com"
  },
  {
    "fullName": "Ahmed Raza",
    "email": "ahmed.raza@example.com",
    "password": "hashed_password_4",
    "profilePhoto": "https://example.com/photos/ahmed.jpg",
    "age": 22,
    "gender": "Male",
    "country": "Pakistan",
    "currentRole": "Student",
    "industryInterest": "Cybersecurity",
    "experienceYears": 0,
    "mentorshipGoals": ["Ethical Hacking", "Certification Guidance"],
    "bio": "Tech enthusiast with a growing interest in network security.",
    "availability": ["Evenings"],
    "languages": ["English", "Urdu"],
    "linkedIn": "https://linkedin.com/in/ahmedraza",
    "website": ""
  },
  {
    "fullName": "Emily Carter",
    "email": "emily.carter@example.com",
    "password": "hashed_password_5",
    "profilePhoto": "https://example.com/photos/emily.jpg",
    "age": 35,
    "gender": "Female",
    "country": "Canada",
    "currentRole": "Senior Data Analyst",
    "industryInterest": "Data Science",
    "experienceYears": 8,
    "mentorshipGoals": ["Leadership Skills", "Data Visualization"],
    "bio": "Data analyst with a passion for mentoring new talent.",
    "availability": ["Weekdays"],
    "languages": ["English", "French"],
    "linkedIn": "https://linkedin.com/in/emilycarter",
    "website": ""
  },
  {
    "fullName": "Hiroshi Tanaka",
    "email": "hiroshi.t@example.com",
    "password": "hashed_password_6",
    "profilePhoto": "https://example.com/photos/hiroshi.jpg",
    "age": 28,
    "gender": "Male",
    "country": "Japan",
    "currentRole": "Software Engineer",
    "industryInterest": "AI & Robotics",
    "experienceYears": 5,
    "mentorshipGoals": ["AI Projects", "Technical Interviews"],
    "bio": "Engineer specializing in robotics and automation.",
    "availability": ["Weekends", "Evenings"],
    "languages": ["Japanese", "English"],
    "linkedIn": "",
    "website": "https://hiroshitech.com"
  },
  {
    "fullName": "Sarah Johnson",
    "email": "sarah.j@example.com",
    "password": "hashed_password_7",
    "profilePhoto": "https://example.com/photos/sarah.jpg",
    "age": 26,
    "gender": "Female",
    "country": "UK",
    "currentRole": "Graduate",
    "industryInterest": "Product Management",
    "experienceYears": 1,
    "mentorshipGoals": ["Career Switching", "Interview Prep"],
    "bio": "Aspiring product manager with a marketing background.",
    "availability": ["Weekdays", "Weekends"],
    "languages": ["English"],
    "linkedIn": "https://linkedin.com/in/sarahjohnson",
    "website": ""
  },
  {
    "fullName": "Mohammed Al-Sayed",
    "email": "mohammed.s@example.com",
    "password": "hashed_password_8",
    "profilePhoto": "https://example.com/photos/mohammed.jpg",
    "age": 32,
    "gender": "Male",
    "country": "UAE",
    "currentRole": "Project Manager",
    "industryInterest": "IT Management",
    "experienceYears": 7,
    "mentorshipGoals": ["Leadership", "Agile Practices"],
    "bio": "Project manager with a focus on delivering quality tech solutions.",
    "availability": ["Weekdays"],
    "languages": ["Arabic", "English"],
    "linkedIn": "https://linkedin.com/in/mohammedalsayed",
    "website": ""
  },
  {
    "fullName": "Olivia Brown",
    "email": "olivia.b@example.com",
    "password": "hashed_password_9",
    "profilePhoto": "https://example.com/photos/olivia.jpg",
    "age": 21,
    "gender": "Female",
    "country": "Australia",
    "currentRole": "Student",
    "industryInterest": "Game Development",
    "experienceYears": 0,
    "mentorshipGoals": ["Unity", "C# Programming"],
    "bio": "Game design student eager to learn from industry experts.",
    "availability": ["Weekends"],
    "languages": ["English"],
    "linkedIn": "",
    "website": ""
  },
  {
    "fullName": "Carlos Mendes",
    "email": "carlos.m@example.com",
    "password": "hashed_password_10",
    "profilePhoto": "https://example.com/photos/carlos.jpg",
    "age": 29,
    "gender": "Male",
    "country": "Brazil",
    "currentRole": "Frontend Developer",
    "industryInterest": "Web Development",
    "experienceYears": 4,
    "mentorshipGoals": ["React", "Career Growth"],
    "bio": "Frontend developer building scalable web applications.",
    "availability": ["Evenings"],
    "languages": ["Portuguese", "English"],
    "linkedIn": "https://linkedin.com/in/carlosmendes",
    "website": ""
  },
  {
    "fullName": "Fatima Zahra",
    "email": "fatima.z@example.com",
    "password": "hashed_password_11",
    "profilePhoto": "https://example.com/photos/fatima.jpg",
    "age": 23,
    "gender": "Female",
    "country": "Morocco",
    "currentRole": "Junior Developer",
    "industryInterest": "Mobile Development",
    "experienceYears": 1,
    "mentorshipGoals": ["Flutter", "App Deployment"],
    "bio": "Mobile app developer with a love for clean UI.",
    "availability": ["Weekdays", "Weekends"],
    "languages": ["Arabic", "French", "English"],
    "linkedIn": "",
    "website": ""
  },
  {
    "fullName": "John Smith",
    "email": "john.smith@example.com",
    "password": "hashed_password_12",
    "profilePhoto": "https://example.com/photos/john.jpg",
    "age": 40,
    "gender": "Male",
    "country": "USA",
    "currentRole": "Tech Lead",
    "industryInterest": "Cloud Computing",
    "experienceYears": 15,
    "mentorshipGoals": ["AWS", "Team Leadership"],
    "bio": "Leading teams in cloud-native architecture solutions.",
    "availability": ["Weekdays"],
    "languages": ["English"],
    "linkedIn": "https://linkedin.com/in/johnsmith",
    "website": "https://johnsmith.io"
  },
  {
    "fullName": "Priya Sharma",
    "email": "priya.s@example.com",
    "password": "hashed_password_13",
    "profilePhoto": "https://example.com/photos/priya.jpg",
    "age": 25,
    "gender": "Female",
    "country": "India",
    "currentRole": "Data Analyst",
    "industryInterest": "Business Intelligence",
    "experienceYears": 2,
    "mentorshipGoals": ["Power BI", "SQL"],
    "bio": "Helping companies make data-driven decisions.",
    "availability": ["Weekends", "Evenings"],
    "languages": ["Hindi", "English"],
    "linkedIn": "",
    "website": ""
  },
  {
    "fullName": "Liam O'Connor",
    "email": "liam.o@example.com",
    "password": "hashed_password_14",
    "profilePhoto": "https://example.com/photos/liam.jpg",
    "age": 33,
    "gender": "Male",
    "country": "Ireland",
    "currentRole": "DevOps Engineer",
    "industryInterest": "Cloud Infrastructure",
    "experienceYears": 6,
    "mentorshipGoals": ["Kubernetes", "CI/CD"],
    "bio": "Specialist in building scalable cloud systems.",
    "availability": ["Weekdays"],
    "languages": ["English", "Irish"],
    "linkedIn": "https://linkedin.com/in/liamoconnor",
    "website": ""
  },
  {
    "fullName": "Noura El-Badri",
    "email": "noura.b@example.com",
    "password": "hashed_password_15",
    "profilePhoto": "https://example.com/photos/noura.jpg",
    "age": 28,
    "gender": "Female",
    "country": "Egypt",
    "currentRole": "AI Researcher",
    "industryInterest": "Artificial Intelligence",
    "experienceYears": 4,
    "mentorshipGoals": ["Research Collaboration", "Publishing Papers"],
    "bio": "AI researcher working on natural language processing.",
    "availability": ["Weekdays", "Weekends"],
    "languages": ["Arabic", "English"],
    "linkedIn": "https://linkedin.com/in/nouraelbadri",
    "website": ""
  },
  {
    "fullName": "Ethan Walker",
    "email": "ethan.w@example.com",
    "password": "hashed_password_16",
    "profilePhoto": "https://example.com/photos/ethan.jpg",
    "age": 19,
    "gender": "Male",
    "country": "New Zealand",
    "currentRole": "Student",
    "industryInterest": "AR/VR",
    "experienceYears": 0,
    "mentorshipGoals": ["Unity", "AR Development"],
    "bio": "AR/VR enthusiast learning 3D modeling and programming.",
    "availability": ["Weekends", "Evenings"],
    "languages": ["English"],
    "linkedIn": "",
    "website": ""
  },
  {
    "fullName": "Sofia Rossi",
    "email": "sofia.r@example.com",
    "password": "hashed_password_17",
    "profilePhoto": "https://example.com/photos/sofia.jpg",
    "age": 31,
    "gender": "Female",
    "country": "Italy",
    "currentRole": "Marketing Specialist",
    "industryInterest": "Digital Marketing",
    "experienceYears": 7,
    "mentorshipGoals": ["SEO", "Content Strategy"],
    "bio": "Helping brands grow through creative digital campaigns.",
    "availability": ["Weekdays"],
    "languages": ["Italian", "English"],
    "linkedIn": "https://linkedin.com/in/sofiarossi",
    "website": ""
  },
  {
    "fullName": "James Parker",
    "email": "james.p@example.com",
    "password": "hashed_password_18",
    "profilePhoto": "https://example.com/photos/james.jpg",
    "age": 27,
    "gender": "Male",
    "country": "USA",
    "currentRole": "Backend Developer",
    "industryInterest": "API Development",
    "experienceYears": 3,
    "mentorshipGoals": ["Microservices", "System Design"],
    "bio": "Backend developer with a focus on scalable APIs.",
    "availability": ["Evenings"],
    "languages": ["English"],
    "linkedIn": "",
    "website": ""
  },
  {
    "fullName": "Zara Patel",
    "email": "zara.p@example.com",
    "password": "hashed_password_19",
    "profilePhoto": "https://example.com/photos/zara.jpg",
    "age": 23,
    "gender": "Female",
    "country": "India",
    "currentRole": "Student",
    "industryInterest": "UI/UX",
    "experienceYears": 0,
    "mentorshipGoals": ["Design Thinking", "Figma"],
    "bio": "Creative thinker exploring UI/UX tools and methods.",
    "availability": ["Weekdays", "Weekends"],
    "languages": ["Hindi", "English"],
    "linkedIn": "https://linkedin.com/in/zarapatel",
    "website": ""
  },
  {
    "fullName": "Omar Farooq",
    "email": "omar.f@example.com",
    "password": "hashed_password_20",
    "profilePhoto": "https://example.com/photos/omar.jpg",
    "age": 36,
    "gender": "Male",
    "country": "Pakistan",
    "currentRole": "Full Stack Developer",
    "industryInterest": "Web Development",
    "experienceYears": 10,
    "mentorshipGoals": ["Mentoring Juniors", "Open Source"],
    "bio": "Full stack developer passionate about community building.",
    "availability": ["Weekdays", "Evenings"],
    "languages": ["English", "Urdu"],
    "linkedIn": "",
    "website": "https://omarfarooq.dev"
  }
]
